// Code generated by hertz generator.

package User

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hertz-contrib/sessions"
	"github.com/hertz-contrib/sessions/cookie"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _infoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		sessions.Sessions("usersession", cookie.NewStore([]byte("secret"))),
	}
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}
